services:
  keyvault-api:
    build: .
    ports:
      - "4444:3000"
    environment:
      RUST_LOG: "debug,sqlx=debug"
      # Postgres connection (Postgres service is on the same 'backend' network)
      PG_HOST:              postgres
      POSTGRES_DB:          ${POSTGRES_DB}
      SECRETS_READ_USER:    ${SECRETS_READ_USER}
      SECRETS_READ_PASSWORD: ${SECRETS_READ_PASSWORD}
      SECRETS_WRITE_USER:   ${SECRETS_WRITE_USER}
      SECRETS_WRITE_PASSWORD: ${SECRETS_WRITE_PASSWORD}
      # per-service API keys
      API_MASTER_KEY_READ:  ${API_MASTER_KEY_READ}
      API_MASTER_KEY_WRITE: ${API_MASTER_KEY_WRITE}
    networks:
      - homelab

  keyvault-ui:
    build: ./keyvault-ui
    ports:
      - "4000:3000" 
    networks:
      - homelab

volumes:
  node_red_data:

networks:
  homelab:
    external: true
